name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Determine Tag Type
        id: tag_check
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          if [[ "$TAG" == *test* ]]; then
            echo "TAG_TYPE=test" >> $GITHUB_ENV
          else
            echo "TAG_TYPE=release" >> $GITHUB_ENV
          fi
          echo "Determined TAG_TYPE: $TAG_TYPE"

      - name: Build Docker image
        run: |
          IMAGE_NAME="bilbs84/cifs-backup"
          VERSION="${GITHUB_REF#refs/tags/}"
          docker build . --file Dockerfile -t $IMAGE_NAME:$VERSION

      - name: Push Docker images
        run: |
          IMAGE_NAME="bilbs84/cifs-backup"
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "Pushing image with TAG_TYPE: $TAG_TYPE"
          docker push $IMAGE_NAME:$VERSION
          if [ "$TAG_TYPE" == "release" ]; then
            echo "Tagging and pushing as latest"
            docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
          else
            echo "Not tagging as latest due to TAG_TYPE: $TAG_TYPE"
          fi
        env:
          TAG_TYPE: ${{ env.TAG_TYPE }}
