name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="bilbs84/cifs-backup"
          VERSION="${GITHUB_REF#refs/tags/}"
          docker build . --file Dockerfile -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest

      - name: Push Docker images
        run: |
          IMAGE_NAME="bilbs84/cifs-backup"
          VERSION="${GITHUB_REF#refs/tags/}"
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
